# Generated by Django 3.1.3 on 2020-11-04 14:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='CPF')),
                ('razao', models.CharField(max_length=255, unique=True, verbose_name='Razão Social')),
                ('codigo_municipio', models.PositiveIntegerField(blank=True, null=True, verbose_name='código do município')),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=50)),
                ('date_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacao', models.DateTimeField(auto_now=True)),
                ('email_caixa_cadastrado', models.BooleanField(default=False)),
                ('cliente_ativo', models.BooleanField(default=True)),
                ('situacao_adimplencia', models.BooleanField(blank=True, default=False)),
                ('sede', models.BooleanField(default=False)),
                ('nome_fantasia', models.CharField(max_length=255, null=True, unique=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOrgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descriçao')),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orgao', to='prestcontas_api.tipoorgao')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacao', models.CharField(blank=True, default='N/A', max_length=255, null=True, verbose_name='Numero/Operaçao')),
                ('siafi_sicony', models.CharField(blank=True, max_length=255, null=True, verbose_name='SIAFI/SICONV')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('termino', models.DateField(blank=True, null=True)),
                ('ano', models.IntegerField()),
                ('prorrogado', models.DateField(blank=True, null=True)),
                ('repasse', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('contrapartida', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('aditivo_valor_adicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('aditivo_valor_supressao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('ultima_modificacao', models.DateTimeField(auto_now=True)),
                ('objeto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('concedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orgao_concedente_instrumento', to='prestcontas_api.orgao')),
                ('entidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prestcontas_api.entidade')),
                ('interveniente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orgao_interveniente_instrumento', to='prestcontas_api.orgao')),
                ('palavra_chave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prestcontas_api.palavrachave')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestcontas_api.tipoinstrumento', verbose_name='Tipo Instrumento')),
            ],
        ),
        migrations.AddField(
            model_name='entidade',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prestcontas_api.tipoentidade'),
        ),
    ]
